#include common cfg makefile 
include ../../Makefile_cfg.mk

#lib specific configuration
TARGET_NAME    := console_player
TARGET_EXT     := out
OWN_LIBS_NAMES := lib_core 

#include common commands makefile 
include ../../Makefile_commands.mk

#include common makefile for app
include ../../Makefile_applications.mk
  



