#include common cfg makefile 
include ../../Makefile_cfg.mk

#lib specific configuration
TARGET_NAME    := lib_core
TARGET_EXT     := a
OWN_LIBS_NAMES :=

#include common commands makefile 
include ../../Makefile_commands.mk

#include common makefile for library
include ../../Makefile_libraries.mk
